### ISSUE TITLE
discuss how best to implement step() in dodo

### ISSUE THREAD

**Issue by radka-j** [alan-turing-institute/dodo#55]
In BlueBird, to use the step() function have to first:
- set SIMMODE to 'agent'
- set DTMULT to what want the step size to be

Only after that is it possible to call step().

Should dodo offer a single step function that executes all of these steps (or something along those line)?

**Comment by rkm** [comment]
You can also start BlueBird with `--sim_mode=agent` to avoid having to set this afterwards. If you're running with the included docker-compose file, then you can also uncomment [this](https://github.com/alan-turing-institute/bluebird/blob/release/1.3.0/docker-compose.yml#L30) line 😃
