### ISSUE TITLE
test_manage_simulation.py::test_load_bluesky - Failure

### ISSUE THREAD

**Issue by tallamjr** [alan-turing-institute/dodo#67]
When examining the issues relating to https://github.com/alan-turing-institute/dodo/pull/64 , I compared the method for
integration tests with what is being done in [simurgh's travis script](https://github.com/alan-turing-institute/simurgh/blob/ef1d33916acdfa66738b2ffa1f77fd395e7662e0/.travis.yml#L45)
This lead to the discovery of where it appeared to be issues with
`load_scenario()` function in `bluebird`

When running the integration tests locally using docker the following test fails:
```bash
...
tests/integration/test_manage_simulation.py::test_simulation_control PASSED
tests/integration/test_manage_simulation.py::test_load_bluesky FAILED
tests/integration/test_manage_simulation.py::test_load_fail PASSED
...
```
With the accompanying error of:
```bash
if http_error_msg:
>           raise HTTPError(http_error_msg, response=self)
E           requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5001/api/v1/ic
```
It appears the test expects the file extension to be lowercase but is in fact
upper case as found in `bluesky/scenario/8.SCN`. A change to
`tests/test_simulation_control.py` should resolve this.

Please see this https://github.com/alan-turing-institute/nats/issues/98 where it outlines the fact that although this appears to be a general issue, it does not seem to arise when one does _not_ use the docker builds

**Comment by rkm** [comment]
This is an issue with using the pre-defined BlueSky scenarios. Some are uppercase and some are lowercase, so we have to do lots of string-mangling to try and guess which case a particular file is (in BlueBird). In general, we should be moving away from using these scenarios, and instead create our own for testing using the upload scenario `/api/v1/scenario` API.
