### ISSUE TITLE
[QUESTION] Potential duplicate functions, `get_position` and `aircraft_position`

### ISSUE THREAD

**Issue by tallamjr** [alan-turing-institute/dodo#76]
Are `get_position` and `aircraft_position` within `pydodo/request_position.py` duplicates of one another. They seem to return the same values but appear to have slightly different implementations.

**Comment by radka-j** [comment]
The `get_position` function is a helper function called by `aircraft_position`

 `get_position` function takes as argument a single aircraft ID and returns its position

`aircraft_position` takes as argument either single aircraft ID or a list of aircraft IDs and returns their position. 

In `aircraft_position` then, if a single aircraft ID is passed then the function just calls `get_position`, if a list is provided then it gets all aircraft positions and filters out the the requested IDs.

Does this make sense? It could probably be simplified! I think in the original implementation, `aircraft_position` would call `get_position` in a loop when a list of IDs was provided but then we decided on the above implementation.

**Comment by tallamjr** [comment]
Makes sense, thanks @radka-j
