### ISSUE TITLE
config.yml hard coded address

### ISSUE THREAD

**Issue by tanner-nats** [alan-turing-institute/dodo#96]
The host address is hard coded to 51.145.47.193
Agent are likely to use their 'localhost' address.
Either update the README to instruct the user to alter the address, or set the default host to 'localhost'.
i.e. 
`python3 run.py default_input_agents_read_scn.ini`
will fail with:
`HTTPConnectionPool(host='51.145.47.193', port=5002): Max retries exceeded with url: /api/v1/reset (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61cee12358>: Failed to establish a new connection: [Errno 110] Connection timed out',))
`

**Comment by radka-j** [comment]
The master version of `dodo` has default `host` as 'localhost'. 

Also, a `bluebird_config` function has now been added that allows setting the bluebird host, port and version values to something other than the config defaults.
